version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo-mynews
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
